# Create a local developmemt conmtainer  (Minicube needs to build a kernel module)

# Pin the version of falco
FROM falcosecurity/falco:0.23.0

# //TODO to use custom intermediate image we need to get eBPF driver working
# Use the acme customized intermediate container to start with
# FROM gcr.io/pm-registry/falco:latest

LABEL repository="https://github.com/acme/security.git"
LABEL maintainer="security@acme.com"
LABEL purpose="siem"

# LABEL vendor=ACME\ Incorporated \
#       com.example.is-beta= \
#       com.example.is-production="" \
#       com.example.version="0.0.1-beta" \
#       com.example.release-date="2015-02-12"

# Install FluentBit package key
RUN curl -L http://packages.fluentbit.io/fluentbit.key | apt-key add -

# Get Current
RUN echo "deb https://packages.fluentbit.io/debian/buster buster main" >> /etc/apt/sources.list
RUN DEBIAN_FRONTEND=noninteractive apt-get -y update \
  && DEBIAN_FRONTEND=noninteractive apt -y --fix-broken install \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common \
  apt-transport-https sudo libgnutls28-dev curl td-agent-bit build-essential linux-source libncurses5-dev

# Customize the Service configuration
COPY /etc/falco/falco.yaml /etc/falco/falco.yaml
# Copy our acme custom rules configu
COPY /etc/falco/falco_rules.local.yaml /etc/falco/falco_rules.local.yaml
# Cluster worker audit rules
COPY /etc/falco/k8s_audit_rules.yaml /etc/falco/k8s_audit_rules.yaml

# Supply our FluentBit configuration to ship events to Sumologic
COPY /etc/td-agent-bit/td-agent-bit.conf /etc/td-agent-bit/td-agent-bit.conf 
COPY /etc/startup.sh /startup.sh

# What are the min permissions Falco process needs
RUN useradd falco
RUN usermod -a -G falco falco
RUN usermod -a -G sudo falco
RUN echo "falco ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN usermod -a -G adm falco
WORKDIR "/home/falco"
USER falco
