apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  creationTimestamp: null
  name: falco-ds-pod-security-policy
  namespace: team-security
spec:
  allowedCapabilities:
  - NET_ADMIN
  - SYS_PTRACE
  allowedHostPaths:
  - pathPrefix: /var/run/calico
    readOnly: true
  - pathPrefix: /var/lib/docker
    readOnly: true
  - pathPrefix: /mnt/disks
    readOnly: true
  - pathPrefix: /var/lib/log-tailer
    readOnly: true
  - pathPrefix: /proc
    readOnly: true
  - pathPrefix: /usr
    readOnly: true
  - pathPrefix: /var/lib/kubelet/pki/
    readOnly: true
  - pathPrefix: /var/run/
    readOnly: true
  - pathPrefix: /sys/fs/cgroup
    readOnly: true
  - pathPrefix: /dev
    readOnly: true
  - pathPrefix: /var/run
    readOnly: true
  - pathPrefix: /dev/disk
    readOnly: true
  - pathPrefix: /boot
    readOnly: true
  - pathPrefix: /usr/share/ca-certificates
    readOnly: true
  - pathPrefix: /etc/cni/net.d
    readOnly: true
  - pathPrefix: /lib/modules
    readOnly: true
  - pathPrefix: /var/lib/kubelet/device-plugins
    readOnly: true
  - pathPrefix: /var/log
    readOnly: true
  - pathPrefix: /var/run/docker.sock
    readOnly: true
  - pathPrefix: /home/kubernetes/bin
    readOnly: true
  - pathPrefix: /etc/srv/kubernetes/pki/
    readOnly: true
  - pathPrefix: /etc/ssl/certs
    readOnly: true
  - pathPrefix: /var/lib/kube-proxy/kubeconfig
    readOnly: true
  - pathPrefix: /var/lib/kubelet/kubeconfig
    readOnly: true
  - pathPrefix: /
    readOnly: true
  - pathPrefix: /var/lib/docker/containers
    readOnly: true
  - pathPrefix: /etc
    readOnly: true
  - pathPrefix: /var/lib/calico
    readOnly: true
  - pathPrefix: /run/xtables.lock
    readOnly: true
  - pathPrefix: /var/lib/kubelet/pods
    readOnly: true
  - pathPrefix: /etc/ssl/certs/
    readOnly: true
  - pathPrefix: /sys
    readOnly: true
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
  - hostPath
  - configMap
